# Generated by Django 5.2.8 on 2026-07-13 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ürün adı')),
                ('category', models.CharField(choices=[('soups', 'Çorbalar'), ('mains', 'Ana Yemekler'), ('desserts', 'Tatlılar'), ('drinks', 'İçecekler')], db_index=True, max_length=20, verbose_name='Kategori')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fiyat')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ('category', 'sort_order', 'name'),
                'indexes': [models.Index(fields=['category', 'is_active', 'sort_order'], name='product_menu_lookup')],
            },
        ),
    ]
