# Generated by Django 5.2.8 on 2026-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_update_tomris_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Örnek: https://www.facebook.com/tomrisrestoran', max_length=300, verbose_name='Facebook bağlantısı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Örnek: https://www.instagram.com/tomrisrestoran', max_length=300, verbose_name='Instagram bağlantısı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Örnek: 0258 263 00 00. Boş bırakılırsa sitede telefon görünmez.', max_length=30, verbose_name='Telefon numarası'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Örnek: 0532 000 00 00. Boş bırakılırsa WhatsApp butonları görünmez.', max_length=30, verbose_name='WhatsApp numarası'),
        ),
    ]
